import { DemoCourse } from './demo-content';

export const webDevCourse: DemoCourse = {
  title: 'Web Development: HTML, CSS & JavaScript Masterclass',
  description: 'HTML5, আধুনিক CSS3 এবং JavaScript এর পূর্ণাঙ্গ ৩-মাইলস্টোন হ্যান্ডস-অন কোর্স। বেসিক সিনট্যাক্স থেকে শুরু করে রিয়েল-ওয়ার্ল্ড ইন্টারঅ্যাক্টিভ ওয়েব প্রজেক্ট তৈরির সম্পূর্ণ গাইড।',
  ownerEmail: 'instructor@demo.test',
  lessons: [
    // -------------------------------------------------------------
    // MILESTONE 1: HTML5 Foundations (5 Modules)
    // -------------------------------------------------------------
    {
      title: 'M1.1: HTML5 Introduction & Document Architecture',
      order: 1,
      videoUrl: 'https://www.youtube.com/watch?v=kUMe1FH4CHE',
      content: [
        '# Milestone 1: HTML Foundations',
        '## Module 1: HTML5 Introduction & Document Architecture',
        '',
        '### 📌 ভূমিকা (Introduction)',
        'HTML (HyperText Markup Language) হলো যেকোনো ওয়েবসাইটের হাড় বা স্কেলেটন (Skeleton)। ব্রাউজার কিভাবে একটি পেজের কন্টেন্ট রেন্ডার করবে তা HTML ডকুমেন্টের মাধ্যমেই নির্ধারিত হয়।',
        '',
        '### 🏗️ HTML5 Standard Document Structure',
        'প্রতিটি আধুনিক ওয়েব পেজের একটি স্ট্যান্ডার্ড বয়লারপ্লেট (Standard Boilerplate) থাকে:',
        '',
        '```html',
        '<!DOCTYPE html>',
        '<html lang="bn">',
        '  <head>',
        '    <meta charset="UTF-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        '    <title>My First Web Page</title>',
        '  </head>',
        '  <body>',
        '    <h1>স্বাগতম CPS Academy তে!</h1>',
        '    <p>এটি আমাদের প্রথম HTML5 ওয়েব পেজ।</p>',
        '  </body>',
        '</html>',
        '```',
        '',
        '### 🔍 গুরুত্বপূর্ণ ট্যাগসমূহের ব্যাখ্যা:',
        '- `<!DOCTYPE html>`: ব্রাউজারকে নির্দেশ করে যে এটি HTML5 স্ট্যান্ডার্ডের ডকুমেন্ট।',
        '- `<html lang="bn">`: ডকুমেন্টের রুট এলিমেন্ট এবং ভাষা নির্দেশ করে।',
        '- `<head>`: মেটাডাটা, টাইটেল, ফন্ট ও স্টাইলশিট লিঙ্কিং ধারণ করে (যা সরাসরি পেজে দৃশ্যমান হয় না)।',
        '- `<meta name="viewport">`: মোবাইল ও রেসপন্সিভ ডিভাইসে পেজ সঠিকভাবে ফিট হওয়ার জন্য আবশ্যক।',
        '- `<body>`: ব্যবহারকারী ব্রাউজার স্ক্রিনে যা কিছু দেখতে পায় (টেক্সট, ইমেজ, বাটন), সব কিছুই বডির ভেতরে থাকে।',
      ].join('\n'),
    },
    {
      title: 'M1.2: Semantic Text Formatting & Content Hierarchy',
      order: 2,
      content: [
        '# Milestone 1: HTML Foundations',
        '## Module 2: Semantic Text Formatting & Content Hierarchy',
        '',
        '### 📌 হেডলাইন ও টেক্সট হায়ারার্কি (Text Hierarchy)',
        'SEO এবং Accessibility-এর জন্য সঠিক হেডিং অর্ডার ব্যবহার করা অত্যন্ত জরুরি। পেজে সবসময় একটি মাত্র `<h1>` ট্যাগ থাকা উচিত।',
        '',
        '```html',
        '<!-- Headings from most to least important -->',
        '<h1>মেইন টাইটেল (Main Page Heading)</h1>',
        '<h2>সেকশন হেডিং (Section Heading)</h2>',
        '<h3>সাব-সেকশন (Sub-section)</h3>',
        '',
        '<!-- Paragraphs & Inline Formatting -->',
        '<p>',
        '  JavaScript শেখার আগে <strong>HTML & CSS</strong> ভালোভাবে বোঝা জরুরি।',
        '  এটি কোডিংকে <em>অনেক সহজ</em> ও অর্থবহ করে তোলে।',
        '</p>',
        '```',
        '',
        '### 📋 লিস্ট ও কোটেশন (Lists & Quotations):',
        '```html',
        '<!-- Unordered List -->',
        '<ul>',
        '  <li>HTML5 Semantic Tags</li>',
        '  <li>CSS Flexbox & Grid</li>',
        '  <li>Modern JavaScript (ES6+)</li>',
        '</ul>',
        '',
        '<!-- Ordered List -->',
        '<ol>',
        '  <li>কনসেপ্ট শিখুন</li>',
        '  <li>হাতে-কলমে প্র্যাকটিস করুন</li>',
        '  <li>প্রজেক্ট তৈরি করুন</li>',
        '</ol>',
        '```',
      ].join('\n'),
    },
    {
      title: 'M1.3: Hyperlinks, Navigation & Media Embedding',
      order: 3,
      content: [
        '# Milestone 1: HTML Foundations',
        '## Module 3: Hyperlinks, Navigation & Media Embedding',
        '',
        '### 🔗 হাইপারলিঙ্ক (`<a>` Anchor Tag)',
        'ওয়েবের মূল প্রাণ হলো লিঙ্ক। এক পেজ থেকে অন্য পেজে বা এক্সটার্নাল লিঙ্কে যেতে `<a>` ট্যাগ ব্যবহার করা হয়:',
        '',
        '```html',
        '<!-- Internal Link -->',
        '<a href="/courses">কোর্স ক্যাটালগ দেখুন</a>',
        '',
        '<!-- External Link opening in a new tab with security attributes -->',
        '<a href="https://developer.mozilla.org" target="_blank" rel="noopener noreferrer">',
        '  MDN Web Docs ভিজিট করুন',
        '</a>',
        '```',
        '',
        '### 🖼️ ইমেজ ও রেসপন্সিভ মিডিয়া (Images & Media)',
        '```html',
        '<figure>',
        '  <img',
        '    src="/images/web-dev.jpg"',
        '    alt="Web development concepts illustration"',
        '    loading="lazy"',
        '    width="600"',
        '    height="400"',
        '  />',
        '  <figcaption>চিত্র ১: ফুলস্ট্যাক ওয়েব ডেভেলপমেন্ট আর্কিটেকচার</figcaption>',
        '</figure>',
        '```',
        '> **Best Practice:** সবসময় `alt` অ্যাট্রিবিউট ব্যবহার করবেন, এটি স্ক্রিন রিডার এবং SEO ফ্রেন্ডলিনেসের জন্য অপরিহার্য।',
      ].join('\n'),
    },
    {
      title: 'M1.4: Modern Semantic HTML5 Layouts',
      order: 4,
      content: [
        '# Milestone 1: HTML Foundations',
        '## Module 4: Modern Semantic HTML5 Layouts',
        '',
        '### 🧱 সিমান্টিক এলিমেন্টস কেন ব্যবহার করবেন?',
        'অপ্রয়োজনীয় `<div>` এর ভিড় এড়িয়ে মিনিংফুল বা অর্থপূর্ণ ট্যাগ ব্যবহার করাই হলো Semantic HTML। এতে সার্চ ইঞ্জিন এবং ব্রাউজার সহজে পেজের কাঠামো বুঝতে পারে।',
        '',
        '```html',
        '<header>',
        '  <nav aria-label="Main Navigation">',
        '    <ul>',
        '      <li><a href="/">Home</a></li>',
        '      <li><a href="/courses">Courses</a></li>',
        '    </ul>',
        '  </nav>',
        '</header>',
        '',
        '<main>',
        '  <article>',
        '    <h2>কীভাবে একজন দক্ষ ডেভেলপার হবেন?</h2>',
        '    <p>নিয়মিত সমস্যা সমাধান এবং প্রজেক্ট তৈরির মাধ্যমে...</p>',
        '    <section>',
        '      <h3>ধাপ ১: ফান্ডামেন্টাল ক্লিয়ার রাখা</h3>',
        '      <p>HTML, CSS এবং JS এর বেসিক স্ট্রং করুন।</p>',
        '    </section>',
        '  </article>',
        '',
        '  <aside>',
        '    <h3>সম্পর্কিত রিসোর্স</h3>',
        '    <p>CPS Academy প্র্যাকটিস কনটেস্টে অংশ নিন।</p>',
        '  </aside>',
        '</main>',
        '',
        '<footer>',
        '  <p>&copy; 2026 CPS Academy. All rights reserved.</p>',
        '</footer>',
        '```',
      ].join('\n'),
    },
    {
      title: 'M1.5: HTML Forms, Input Types & Client-side Validation',
      order: 5,
      content: [
        '# Milestone 1: HTML Foundations',
        '## Module 5: HTML Forms, Input Types & Client-side Validation',
        '',
        '### 📝 ইউজার ইনপুট ও ফর্ম আর্কিটেকচার',
        'ইউজারের কাছ থেকে ডাটা গ্রহণ করার মূল মাধ্যম হলো `<form>`। প্রতিটি ইনপুটের সাথে একটি পরিষ্কার `<label>` থাকা আবশ্যক।',
        '',
        '```html',
        '<form action="/api/register" method="POST" class="auth-form">',
        '  <div>',
        '    <label for="username">ইউজারনেম (Username):</label>',
        '    <input',
        '      type="text"',
        '      id="username"',
        '      name="username"',
        '      required',
        '      minlength="3"',
        '      placeholder="যেমন: fazlu_dev"',
        '    />',
        '  </div>',
        '',
        '  <div>',
        '    <label for="user-email">ইমেইল (Email):</label>',
        '    <input',
        '      type="email"',
        '      id="user-email"',
        '      name="email"',
        '      required',
        '      placeholder="you@example.com"',
        '    />',
        '  </div>',
        '',
        '  <div>',
        '    <label for="track">ট্র্যাক নির্বাচন করুন:</label>',
        '    <select id="track" name="track">',
        '      <option value="frontend">Frontend Track</option>',
        '      <option value="backend">Backend Track</option>',
        '      <option value="fullstack">Fullstack Track</option>',
        '    </select>',
        '  </div>',
        '',
        '  <button type="submit">রেজিস্ট্রেশন সম্পন্ন করুন</button>',
        '</form>',
        '```',
      ].join('\n'),
    },

    // -------------------------------------------------------------
    // MILESTONE 2: CSS Mastery & HTML Integration (5 Modules)
    // -------------------------------------------------------------
    {
      title: 'M2.1: CSS3 Fundamentals, Selectors & The Cascade',
      order: 6,
      videoUrl: 'https://www.youtube.com/watch?v=1PnVor36_40',
      content: [
        '# Milestone 2: CSS Mastery & HTML Integration',
        '## Module 6: CSS3 Fundamentals, Selectors & The Cascade',
        '',
        '### 🎨 CSS কিভাবে কাজ করে? (The Cascade & Specificity)',
        'CSS (Cascading Style Sheets) ডকুমেন্টের প্রেজেন্টেশন ও লুক অ্যান্ড ফিল নির্ধারণ করে। ক্যাসকেড নিয়ম অনুসারে কোন স্টাইলটি প্রাধান্য পাবে তা সিলেক্টরের স্পেসিফিসিটি (Specificity) দ্বারা নির্ধারিত হয়:',
        '',
        '1. **Inline Styles** (`style="..."`): সর্বোচ্চ প্রাধান্য (1, 0, 0, 0)',
        '2. **ID Selector** (`#header`): (0, 1, 0, 0)',
        '3. **Class / Attribute / Pseudo-class** (`.btn`, `[type="text"]`, `:hover`): (0, 0, 1, 0)',
        '4. **Element Selector** (`div`, `p`, `h1`): (0, 0, 0, 1)',
        '',
        '```css',
        '/* CSS Variables (Custom Properties) */',
        ':root {',
        '  --primary-color: #0c3944;',
        '  --accent-color: #f97316;',
        '  --text-dark: #0f172a;',
        '  --font-main: "Plus Jakarta Sans", sans-serif;',
        '}',
        '',
        'body {',
        '  font-family: var(--font-main);',
        '  color: var(--text-dark);',
        '  margin: 0;',
        '  padding: 0;',
        '}',
        '',
        '/* Reusable Button Style */',
        '.btn-primary {',
        '  background-color: var(--primary-color);',
        '  color: #ffffff;',
        '  padding: 0.625rem 1.25rem;',
        '  border-radius: 0.375rem;',
        '  border: none;',
        '  cursor: pointer;',
        '  transition: transform 0.2s ease, background-color 0.2s ease;',
        '}',
        '',
        '.btn-primary:hover {',
        '  background-color: #082830;',
        '  transform: translateY(-1px);',
        '}',
        '```',
      ].join('\n'),
    },
    {
      title: 'M2.2: The CSS Box Model, Borders & Shadows',
      order: 7,
      content: [
        '# Milestone 2: CSS Mastery & HTML Integration',
        '## Module 7: The CSS Box Model, Borders & Shadows',
        '',
        '### 📦 বক্স মডেল আর্কিটেকচার (Box Model Anatomy)',
        'ব্রাউজারে প্রতিটি এলিমেন্ট মূলত একটি চারকোনা বক্স। এর ৪টি মূল লেয়ার থাকে:',
        '1. **Content**: ভেতরের টেক্সট বা ইমেজ।',
        '2. **Padding**: কন্টেন্ট এবং বর্ডারের মধ্যকার অভ্যন্তরীণ ফাঁকা জায়গা।',
        '3. **Border**: প্যাডিংয়ের চারপাশের আউটলাইন।',
        '4. **Margin**: এই বক্স ও আশেপাশের অন্য বক্সগুলোর মধ্যকার বাহ্যিক ব্যবধান।',
        '',
        '```css',
        '/* গ্লোবাল বক্স-সাইজিং রিসেট - সবসময় ব্যবহার করুন */',
        '*, *::before, *::after {',
        '  box-sizing: border-box;',
        '  margin: 0;',
        '  padding: 0;',
        '}',
        '',
        '/* Card Component with Smooth Elevation */',
        '.course-card {',
        '  background: #ffffff;',
        '  padding: 1.5rem;',
        '  border: 1px solid #e2e8f0;',
        '  border-radius: 0.5rem;',
        '  margin-bottom: 1.5rem;',
        '  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -2px rgba(0, 0, 0, 0.05);',
        '  transition: box-shadow 0.2s ease, border-color 0.2s ease;',
        '}',
        '',
        '.course-card:hover {',
        '  border-color: #cbd5e1;',
        '  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.05);',
        '}',
        '```',
      ].join('\n'),
    },
    {
      title: 'M2.3: Flexbox Architecture & 1D Layout System',
      order: 8,
      content: [
        '# Milestone 2: CSS Mastery & HTML Integration',
        '## Module 8: Flexbox Architecture & 1D Layout System',
        '',
        '### 📐 ফ্লেক্সবক্স দিয়ে ওয়ান-ডাইমেনশনাল লেআউট (1D Layout)',
        'Flexbox ব্যবহার করে সারি (Row) বা কলাম (Column) বরাবর এলিমেন্টগুলোকে খুব সহজে অ্যালাইন ও স্পেস ডিস্ট্রিবিউট করা যায়।',
        '',
        '```html',
        '<header class="navbar">',
        '  <div class="logo">CPS Academy</div>',
        '  <nav class="nav-links">',
        '    <a href="#courses">Courses</a>',
        '    <a href="#quiz">Quiz</a>',
        '    <a href="#blog">Blog</a>',
        '  </nav>',
        '  <button class="btn-primary">Sign In</button>',
        '</header>',
        '```',
        '',
        '```css',
        '.navbar {',
        '  display: flex;',
        '  justify-content: space-between; /* দুই প্রান্তে এলিমেন্ট ছড়ানো */',
        '  align-items: center;            /* উল্লম্বভাবে সেন্টারিং */',
        '  padding: 1rem 2rem;',
        '  background-color: #ffffff;',
        '  border-bottom: 1px solid #e2e8f0;',
        '}',
        '',
        '.nav-links {',
        '  display: flex;',
        '  gap: 1.5rem; /* লিঙ্কগুলোর মাঝে সমান ব্যবধান */',
        '}',
        '',
        '.nav-links a {',
        '  text-decoration: none;',
        '  color: #475569;',
        '  font-weight: 500;',
        '}',
        '',
        '.nav-links a:hover {',
        '  color: #0c3944;',
        '}',
        '```',
      ].join('\n'),
    },
    {
      title: 'M2.4: CSS Grid Mastery & Complex 2D Layouts',
      order: 9,
      content: [
        '# Milestone 2: CSS Mastery & HTML Integration',
        '## Module 9: CSS Grid Mastery & Complex 2D Layouts',
        '',
        '### 📊 CSS Grid দিয়ে দ্বিমাত্রিক (2D) লেআউট',
        'যখন একসাথে রো এবং কলাম দুটিই নিয়ন্ত্রণ করতে হয় (যেমন ড্যাশবোর্ড বা কোর্স ক্যাটালগ গ্রিড), তখন CSS Grid সবচেয়ে পাওয়ারফুল টুল।',
        '',
        '```html',
        '<div class="course-grid">',
        '  <article class="course-item">Course 1: HTML5</article>',
        '  <article class="course-item">Course 2: CSS3</article>',
        '  <article class="course-item">Course 3: JavaScript</article>',
        '  <article class="course-item">Course 4: React.js</article>',
        '</div>',
        '```',
        '',
        '```css',
        '.course-grid {',
        '  display: grid;',
        '  /* স্ক্রিন সাইজ অনুযায়ী অটোমেটিক কলাম তৈরি হবে */',
        '  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));',
        '  gap: 1.5rem;',
        '  padding: 2rem;',
        '}',
        '',
        '.course-item {',
        '  background: #f8fafc;',
        '  border: 1px solid #e2e8f0;',
        '  padding: 2rem;',
        '  border-radius: 0.5rem;',
        '}',
        '```',
      ].join('\n'),
    },
    {
      title: 'M2.5: Responsive Web Design & HTML+CSS Component Project',
      order: 10,
      content: [
        '# Milestone 2: CSS Mastery & HTML Integration',
        '## Module 10: Responsive Web Design & HTML+CSS Component Project',
        '',
        '### 📱 মোবাইল-ফার্স্ট রেসপন্সিভ ডিজাইন (Mobile-First Media Queries)',
        'ছোট স্ক্রিনের জন্য প্রথমে স্টাইল লিখে পরবর্তীতে বড় স্ক্রিনের জন্য `@media (min-width: ...)` ব্যবহার করা আধুনিক স্ট্যান্ডার্ড।',
        '',
        '```html',
        '<div class="pricing-card highlighted">',
        '  <span class="badge">জনপ্রিয়</span>',
        '  <h3>Fullstack Pro</h3>',
        '  <div class="price">৳৫,৯৯৯ <span>/ আজীবন</span></div>',
        '  <ul class="features">',
        '    <li>✓ HTML, CSS ও JS ফুল কোর্স</li>',
        '    <li>✓ রিয়েল লাইফ প্রজেক্ট ও কুইজ</li>',
        '    <li>✓ সার্টিফিকেট ও মেন্টর সাপোর্ট</li>',
        '  </ul>',
        '  <button class="btn-enroll">এখনই ভর্তি হোন</button>',
        '</div>',
        '```',
        '',
        '```css',
        '.pricing-card {',
        '  width: 100%;',
        '  padding: 1.5rem;',
        '  border-radius: 0.75rem;',
        '  background: #ffffff;',
        '  border: 2px solid #0c3944;',
        '  text-align: center;',
        '}',
        '',
        '/* ট্যাবলেট ও ডেস্কটপ স্ক্রিনের জন্য */',
        '@media (min-width: 768px) {',
        '  .pricing-card {',
        '    max-width: 380px;',
        '    margin: 0 auto;',
        '    padding: 2.5rem;',
        '  }',
        '}',
        '```',
      ].join('\n'),
    },

    // -------------------------------------------------------------
    // MILESTONE 3: JavaScript Programming & Full Integration (5 Modules)
    // -------------------------------------------------------------
    {
      title: 'M3.1: JavaScript Foundations: Variables, Types & Operators',
      order: 11,
      videoUrl: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
      content: [
        '# Milestone 3: JavaScript Programming & Full Integration',
        '## Module 11: JavaScript Foundations: Variables, Types & Operators',
        '',
        '### ⚡ জাভাস্ক্রিপ্ট কী এবং কেন?',
        'HTML কাঠামো দেয়, CSS সাজায়, আর JavaScript ওয়েব পেজকে জীবিত ও ইন্টারঅ্যাক্টিভ করে তোলে।',
        '',
        '### 📦 ভেরিয়েবল ডিক্লারেশন (`let` vs `const`):',
        'আধুনিক জাভাস্ক্রিপ্টে `var` পরিহার করে সবসময় `const` (যা পরিবর্তন হবে না) এবং প্রয়োজনে `let` ব্যবহার করুন।',
        '',
        '```javascript',
        '// Primitives & Data Types',
        'const courseName = "Web Development Masterclass"; // String',
        'const totalModules = 15;                          // Number',
        'const isEnrolled = true;                           // Boolean',
        'let currentScore = null;                          // Null (intentional empty)',
        'let studentFeedback;                              // Undefined',
        '',
        '// Template Literals (String Interpolation)',
        'console.log(`কোর্স: ${courseName} | মোট মডিউল: ${totalModules}`);',
        '',
        '// Strict Equality vs Loose Equality',
        'console.log(5 === "5"); // false (Always use ===)',
        'console.log(5 == "5");  // true (Avoid ==)',
        '```',
      ].join('\n'),
    },
    {
      title: 'M3.2: Control Flow, Functions & Scope in JavaScript',
      order: 12,
      content: [
        '# Milestone 3: JavaScript Programming & Full Integration',
        '## Module 12: Control Flow, Functions & Scope in JavaScript',
        '',
        '### 🔀 কন্ডিশনাল লজিক ও ফাংশন আর্কিটেকচার',
        'লজিক্যাল সিদ্ধান্ত গ্রহণ এবং কোড পুনর্ব্যবহারের জন্য ফাংশন ব্যবহৃত হয়।',
        '',
        '```javascript',
        '// Arrow Function with Default Parameters',
        'const calculateDiscount = (price, discountPercent = 10) => {',
        '  if (typeof price !== "number" || price <= 0) {',
        '    return "ইনভ্যালিড প্রাইস";',
        '  }',
        '',
        '  const discountAmount = (price * discountPercent) / 100;',
        '  const finalPrice = price - discountAmount;',
        '  return finalPrice;',
        '};',
        '',
        'const regularPrice = 5000;',
        'const discountedPrice = calculateDiscount(regularPrice, 20);',
        'console.log(`ডিসকাউন্টের পর মূল্য: ৳${discountedPrice}`); // ৳4000',
        '',
        '// Ternary Operator for concise checks',
        'const passStatus = discountedPrice <= 4000 ? "Affordable" : "Standard";',
        '```',
      ].join('\n'),
    },
    {
      title: 'M3.3: Data Structures & ES6+ Methods (map, filter, reduce)',
      order: 13,
      content: [
        '# Milestone 3: JavaScript Programming & Full Integration',
        '## Module 13: Data Structures & ES6+ Methods (map, filter, reduce)',
        '',
        '### 📊 অ্যারে ও অবজেক্ট ম্যানিপুলেশন (Modern Array Methods)',
        'রিয়েল-ওয়ার্ল্ড অ্যাপ্লিকেশনে ডাটা প্রসেসিংয়ের জন্য `map`, `filter`, এবং `reduce` প্রতিনিয়ত ব্যবহৃত হয়।',
        '',
        '```javascript',
        'const courses = [',
        '  { id: 1, title: "HTML5 Basics", price: 1000, active: true },',
        '  { id: 2, title: "CSS3 & Flexbox", price: 1500, active: true },',
        '  { id: 3, title: "Legacy PHP", price: 800, active: false },',
        '  { id: 4, title: "Modern JavaScript", price: 2500, active: true }',
        '];',
        '',
        '// 1. Filter: শুধুমাত্র অ্যাক্টিভ কোর্সগুলো ফিল্টার করা',
        'const activeCourses = courses.filter(course => course.active);',
        '',
        '// 2. Map: শুধুমাত্র টাইটেলগুলোর লিস্ট তৈরি করা',
        'const courseTitles = activeCourses.map(course => course.title);',
        'console.log(courseTitles); // ["HTML5 Basics", "CSS3 & Flexbox", "Modern JavaScript"]',
        '',
        '// 3. Reduce: মোট প্রাইস হিসাব করা',
        'const totalCost = activeCourses.reduce((sum, course) => sum + course.price, 0);',
        'console.log(`মোট সক্রিয় কোর্স মূল্য: ৳${totalCost}`); // ৳5000',
        '```',
      ].join('\n'),
    },
    {
      title: 'M3.4: DOM Manipulation, Event Listeners & Dynamic UI',
      order: 14,
      content: [
        '# Milestone 3: JavaScript Programming & Full Integration',
        '## Module 14: DOM Manipulation, Event Listeners & Dynamic UI (HTML + CSS + JS)',
        '',
        '### 🎯 ব্রাউজার DOM ম্যানিপুলেশন ও ইন্টারেক্টিভিটি',
        'JavaScript দিয়ে সরাসরি HTML এলিমেন্ট সিলেক্ট করা, টেক্সট পরিবর্তন করা, CSS ক্লাস টগল করা এবং ইউজারের ক্লিকে রেসপন্ড করার টেকনিক:',
        '',
        '```html',
        '<div id="counter-app" class="card">',
        '  <h3>Interactive Lesson Progress Counter</h3>',
        '  <p id="count-display">Completed: 0 / 15</p>',
        '  <button id="increment-btn" class="btn">Mark Lesson Done</button>',
        '  <button id="reset-btn" class="btn-secondary">Reset</button>',
        '</div>',
        '```',
        '',
        '```javascript',
        '// DOM Elements Selection',
        'const countDisplay = document.getElementById("count-display");',
        'const incrementBtn = document.getElementById("increment-btn");',
        'const resetBtn = document.getElementById("reset-btn");',
        '',
        'let completedLessons = 0;',
        'const total = 15;',
        '',
        'const updateUI = () => {',
        '  countDisplay.textContent = `Completed: ${completedLessons} / ${total}`;',
        '  if (completedLessons === total) {',
        '    countDisplay.style.color = "#16a34a"; // Green',
        '    incrementBtn.disabled = true;',
        '  }',
        '};',
        '',
        'incrementBtn.addEventListener("click", () => {',
        '  if (completedLessons < total) {',
        '    completedLessons++;',
        '    updateUI();',
        '  }',
        '});',
        '',
        'resetBtn.addEventListener("click", () => {',
        '  completedLessons = 0;',
        '  incrementBtn.disabled = false;',
        '  countDisplay.style.color = "#0f172a";',
        '  updateUI();',
        '});',
        '```',
      ].join('\n'),
    },
    {
      title: 'M3.5: Async/Await, Fetch API & Interactive Web Application Project',
      order: 15,
      content: [
        '# Milestone 3: JavaScript Programming & Full Integration',
        '## Module 15: Async/Await, Fetch API & Interactive Web Application Project',
        '',
        '### 🌐 API কলিং ও রিয়েল-টাইম ইন্টারেক্টিভ প্রজেক্ট',
        'সার্ভার থেকে অ্যাসিনক্রোনাসভাবে ডাটা ফেচ করে ব্রাউজারে ডাইনামিক UI রেন্ডার করার কমপ্লিট উদাহরণ:',
        '',
        '```javascript',
        '// Async function to fetch and render student data',
        'async function loadCourseRoster() {',
        '  const container = document.getElementById("student-list");',
        '  container.innerHTML = "<p class=\"loading\">ডাটা লোড হচ্ছে...</p>";',
        '',
        '  try {',
        '    const response = await fetch("https://jsonplaceholder.typicode.com/users?_limit=4");',
        '    ',
        '    if (!response.ok) {',
        '      throw new Error(`সার্ভার এরর: ${response.status}`);',
        '    }',
        '',
        '    const students = await response.json();',
        '    ',
        '    // ডাইনামিক HTML জেনারেশন',
        '    container.innerHTML = students',
        '      .map(',
        '        (student) => `',
        '        <div class="student-card">',
        '          <h4>${student.name}</h4>',
        '          <p>📧 ${student.email}</p>',
        '          <span class="status-badge">এনরোলড শিক্ষার্থী</span>',
        '        </div>',
        '      `',
        '      )',
        '      .join("");',
        '  } catch (error) {',
        '    container.innerHTML = `<p class="error">ডাটা লোড করা যায়নি: ${error.message}</p>`;',
        '  }',
        '}',
        '',
        '// পেজ লোড হলে ফেচ কল করুন',
        'document.addEventListener("DOMContentLoaded", loadCourseRoster);',
        '```',
        '',
        '### 🎉 অভিনন্দন!',
        'আপনি সফলভাবে HTML5, আধুনিক CSS3 এবং JavaScript এর ৩টি মাইলস্টোন সম্পন্ন করেছেন। এখন নিচের কুইজ অ্যাসেসমেন্টে অংশ নিয়ে নিজের প্রস্তুতি যাচাই করে নিন!',
      ].join('\n'),
    },
  ],
  quiz: {
    title: 'HTML, CSS & JavaScript Comprehensive Assessment',
    questions: [
      {
        text: 'HTML5 ডকুমেন্টে কোন ট্যাগটি সার্চ ইঞ্জিন ও মেটাডাটা কনফিগারেশনের জন্য ব্যবহৃত হয়?',
        options: ['<body>', '<head>', '<main>', '<section>'],
        correctIndex: 1,
      },
      {
        text: 'কোন CSS প্রোপার্টি ব্যবহারের ফলে প্যাডিং এবং বর্ডার এলিমেন্টের মোট উইডথের মধ্যে অন্তর্ভুক্ত থাকে?',
        options: ['box-sizing: content-box', 'box-sizing: border-box', 'display: flex', 'overflow: hidden'],
        correctIndex: 1,
      },
      {
        text: 'Flexbox এ আইটেমগুলোকে হরাইজোন্টালি (Main Axis বরাবর) দুই প্রান্তে স্পেস দিয়ে ছড়ানোর জন্য কোনটি সঠিক?',
        options: ['align-items: center', 'justify-content: space-between', 'flex-direction: column', 'align-content: stretch'],
        correctIndex: 1,
      },
      {
        text: 'জাভাস্ক্রিপ্টে একটি অ্যারেকে রূপান্তর করে সমপরিমাণ নতুন উপাদানসহ নতুন অ্যারে ফেরত পেতে কোন মেথড ব্যবহৃত হয়?',
        options: ['filter()', 'forEach()', 'map()', 'reduce()'],
        correctIndex: 2,
      },
      {
        text: 'নিচের কোন ভেরিয়েবল ডিক্লারেশনটি রি-অ্যাসাইন (Reassign) করার অনুমতি দেয় না?',
        options: ['let', 'const', 'var', 'function'],
        correctIndex: 1,
      },
      {
        text: 'ব্রাউজারে একটি বাটনে ক্লিক ইভেন্ট লিসেনার যুক্ত করার সঠিক সিনট্যাক্স কোনটি?',
        options: [
          'button.attach("click", fn)',
          'button.addEventListener("click", fn)',
          'button.listenClick(fn)',
          'button.on("click", fn)',
        ],
        correctIndex: 1,
      },
      {
        text: 'CSS Grid এ বিভিন্ন স্ক্রিন সাইজে অটোমেটিক কলাম তৈরি ও রেসপন্সিভ গ্রিড বানানোর জন্য কোনটি সবচেয়ে কার্যকর?',
        options: [
          'grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))',
          'display: inline-block',
          'float: left',
          'position: absolute',
        ],
        correctIndex: 0,
      },
      {
        text: 'HTML এ স্ক্রিন রিডার ও ইমেজ লোড না হলে বিকল্প টেক্সট দেখানোর জন্য কোন অ্যাট্রিবিউটটি আবশ্যক?',
        options: ['title', 'alt', 'src', 'href'],
        correctIndex: 1,
      },
      {
        text: 'অ্যাসিনক্রোনাস জাভাস্ক্রিপ্টে API কল করার সময় প্রমিজ সমাধান হওয়া পর্যন্ত কোড এক্সিকিউশন পজ রাখার জন্য কোনটি ব্যবহৃত হয়?',
        options: ['await', 'defer', 'yield', 'delay()'],
        correctIndex: 0,
      },
      {
        text: 'ব্রাউজার রিলোড বা ট্যাব বন্ধ করলেও ব্রাউজারে ইউজার ডাটা স্থায়ীভাবে জমা রাখতে কোনটি ব্যবহৃত হয়?',
        options: ['sessionStorage', 'localStorage', 'cookie (session)', 'Global Variable'],
        correctIndex: 1,
      },
    ],
  },
};
